[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:auth]
command=node /app/backend/services/auth/dist/services/auth/src/main.js
autostart=true
autorestart=true
environment=PORT=4101
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:student]
command=node /app/backend/services/student/dist/main.js
autostart=true
autorestart=true
environment=PORT=4102
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:attendance]
command=node /app/backend/services/attendance/dist/main.js
autostart=true
autorestart=true
environment=PORT=4103
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:academic]
command=node /app/backend/services/academic/dist/main.js
autostart=true
autorestart=true
environment=PORT=4104
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:finance]
command=node /app/backend/services/finance/dist/main.js
autostart=true
autorestart=true
environment=PORT=4105
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:notification]
command=node /app/backend/services/notification/dist/main.js
autostart=true
autorestart=true
environment=PORT=4106
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:communication]
command=node /app/backend/services/communication/dist/main.js
autostart=true
autorestart=true
environment=PORT=4107
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:timetable]
command=node /app/backend/services/timetable/dist/main.js
autostart=true
autorestart=true
environment=PORT=4108
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
